### PR TITLE
[FEATURE] Bouncy animated loading animation

### PR DESCRIPTION
**Pull request by felipe-developer**
Simple and clean bouncy animation with CSS3.

### CODE REVIEW

**Comment by equinusocio** [comment]
@felipe-developer I think you should remove vendor prefixes..they are useles

**Comment by atomiks** [comment]
@equinusocio yep keep everything standard/prefixless. I'm thinking about adding a button to autoprefix the code to be copied soon.

**Comment by felipe-developer** [comment]
Thanks, @equinusocio and @atomiks . Corrections made. Now it's correct?

**Comment by atomiks** [comment]
`-webkit-transform` is being used in `@keyframes` under CSS

**Comment by felipe-developer** [comment]
No more. -webkit-transform has been deleted.

**Comment by atomiks** [comment]
I'm still seeing it under the first css block

**Comment by felipe-developer** [comment]
@atomiks excuse me. Now it's okay.

**Comment by atomiks** [comment]
Seems mostly fine now, except a few things I'll manually fix myself later today.

Before I merge this though, I think I want to finish up categorization/tagging because having tons of loaders it kind of random in the current format.

**Comment by equinusocio** [comment]
@atomiks i think we should also add the `will-change` property.. :)

**Pull request merged**
