### PR TITLE
Format all supported files with Prettier and refactor the script

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by lipis** [comment]
While it looks like all the files are formatted with Prettier it was done most likely from user's editors and not via a script.

I could also add some commit hooks to automate the process.

**Comment by atomiks** [comment]
Yup needed to do this due to inconsistencies with indentation etc. Thank you 😅

**Comment by atomiks** [comment]
Edit: it seems to prettify the `.cache/*.json` files, anyway to ignore that?

**Comment by lipis** [comment]
yep.. my bad #71

**Pull request merged**
