### PR TITLE
[FIX] Use px values for pretty text underline

### PR DESCRIPTION
**Pull request by atomiks**
#22 

@xori can you check if using `px` instead fixes it?

### CODE REVIEW

**Comment by atomiks** [comment]
After testing with others, it seems it looks even worse. I am guessing it's dependent on the font.

Here's a list of the different methods: https://css-tricks.com/styling-underlines-web/

**Comment by xori** [comment]
obligatory screenshot with `background-position: 0 1.1em`.
image
Chrome 64, Win 10

The funny thing about this bug is that Chrome automatically does this by default now.
image

**Comment by Chalarangelo** [comment]
The technique used so far is font-dependent, so this might not be the best idea. If we decide to stick with that, it will require us to add a caveat for the need of a fixed font and work with something like `Arial` which is always installed. Otherwise, we can look into other techniques, based on browser support.

**Comment by Chalarangelo** [comment]
**Update:** It seems like until `text-decoration` styling is fully supported (and it's not even close), we need to stick with the current technique. Adding a caveat and switching the font should do the trick. Adding a link to the CSS tricks article highlighting these techniques along with the reason we are not using the `text-decoration` styling might be a good idea and should help out developers until these features become standard across all platforms (hopefully soon enough).

**Comment by equinusocio** [comment]
I think think this method also depends on `line-height`.

**Comment by charakterziffer** [comment]
For comparison: The demo field with three different fonts and their possible “underline value” (extreme examples for clarification). It does not depend on font size or line-height, but on the internal metrics of a certain font (the proportions of the descenders, ascenders, x-height and the bounding-box).

underline-values

The solution here would be to decide for a consistent font across systems, so a webfont or a websafe font (Verdana, Georgia, Arial, Palatino, Times (New Roman), Trebuchet, Courier (New), Comic Sans).

**Comment by atomiks** [comment]
@charakterziffer interesting. Which is best for `Arial`, as we'll need to switch to that? For a website, they would not be able to use system fonts with this method.

**Comment by charakterziffer** [comment]
`.98em` seems to be a good value for Arial. You could add some fallback fonts that match the font metrics: `font-family: Helvetica, Arial, sans-serif`.

You could leave out alternatives for Linux, like FreeSans, Arimo, or Liberation Sans. They are designed to have the same metrics as Helvetica (as was Arial) and are aliases to replace Arial automatically (see <https://wiki.archlinux.org/index.php/Metric-compatible_fonts#List_of_metric-compatible_fonts>).

Of Helvetica Neue I don’t now the metrics. It’s a redesign of Helvetica used on newer Apple systems – but I guess they didn’t change the metrics that much to stay compatible. You could add it at the beginning of the font stack.

**Pull request merged**
