### PR TITLE
Improve ::selection example and description

### PR DESCRIPTION
**Pull request by equinusocio**
This PR will:

- [x] Improve the `::selection` demo by adding a global style example
- [x] Improve the `::selection` description.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
My only concern about this is that adding a global style like that in the demo will affect the whole site. This could cause some issues, so maybe the snippet example could be tweaked to counteract that.

**Comment by equinusocio** [comment]
@Chalarangelo done 👍

**Comment by atomiks** [comment]
Can you redo this PR without building any files? I think it will override the current changes that have been done.

**Comment by equinusocio** [comment]
@Chalarangelo Thank you.

**Comment by equinusocio** [comment]
@atomiks I don't see this fix live, is this normal?

**Comment by Chalarangelo** [comment]
@equinusocio Yup, we need to actually rebuild the website. Nothing to worry about!

**Pull request merged**
